mecanica de hp/game_over e seus testes implementados
Bassani-Paulo/Projeto-MC656 pull request #10
Opened 2024-09-27 12:47 UTC by gustavoamaraal

pull feature 7

2024-09-27 18:56 UTC, Bassani-Paulo commented on Jogo/scenes/Tartaruga/Jogo.tscn
> +[node name="hp_label" type="Label" parent="Hud"]
É bom deixar o nome de nós com inicial maiúscula

2024-09-27 18:57 UTC, Bassani-Paulo commented on Jogo/scripts/Hud.gd
Não precisa criar um script se ele não vai ser usado

2024-09-27 18:59 UTC, Bassani-Paulo commented on Jogo/scripts/Jogo da Tartaruga.gd
> +var max_hp: int
Como isso é um valor constante, use const e não var. (é bom deixar o nome de constantes todo em letras maiúsculas também)

2024-09-27 19:07 UTC, Bassani-Paulo commented on Jogo/scripts/Jogo da Tartaruga.gd
> +var player_alive: bool
pelo que eu entendi, essa variável existe só pra testar o funcionamento da função game_over(). Não precisa, com Gut da pra vc verificar se uma função foi chamada com assert_called()

2024-09-27 19:09 UTC, Bassani-Paulo commented on Jogo/scripts/Jogo da Tartaruga.gd
> +	update_hp_label()
Coisa boba, mas acho bom deixar esses update do label o mais próximo da linha que muda o player_hp possível. Assim fica mais fácil de ver que ta dando o update por causa da mudança no valor da variável

2024-09-27 19:14 UTC, Bassani-Paulo commented on Jogo/tests/test_hp.gd
> +	player = PlayerScene.instantiate()
Você deu uma cena de "Jogo" a uma variável chamada "player". Não é condizente, mude o nome da variável pra pra "jogo"

2024-09-27 19:59 UTC, Caiozotex submitted a review, later dismissed
Funções sugeridas foram implementadas corretamente. Como o Bassani disse existe algumas coisas que devem ser mudadas , mas são pequenas alterações apenas.
Os testes são condizentes com o que foi proposto.
Ótimo trabalho !!

2024-09-28 01:06 UTC, Bassani-Paulo requested changes
Arrumar ou contestar os comentários

2024-10-02 16:41 UTC, Bassani-Paulo requested changes

2024-10-02 16:41 UTC, Bassani-Paulo commented on Jogo/tests/test_hp.gd
Perdão por não ter reparado isso antes, mas não é legal você ficar chamando "jogo.player_hp =3" (idealmente atributos seriam privados, mas não mude isso pq não estamos deixando nada privado nas outras classes também).
É melhor você testar o funcionamento da função _ready() que já vai setar o valor inicial pra você.
Para acionar a função _ready() é acionada quando a cena é adicionada na árvore de cenas. Para fazer isso faça: add_child(jogo).

2024-10-03 12:14 UTC, Bassani-Paulo approved these changes

2024-10-03 18:47 UTC, DaviGabrielBC approved these changes
Código brabo

2024-10-10 17:42 UTC, merged