Implementação da movimentação e testes
Bassani-Paulo/Projeto-MC656 pull request #18
Opened 2024-10-03 18:53 UTC by DaviGabrielBC

2024-10-04 16:53 UTC, Bassani-Paulo requested changes
A esse ponto, já foi feita tanta besteira no repositório que o "files changed" não está mostrando tudo que mudou em relação à develop original.
Favor remover todos os valores arbritrarios do código (como offsets de posição), isso vai dar conflito. a imagem da tartaruga não vai ficar aparecendo bonitinha na simulação, mas isso é coisa pra uma issue futura.
O arquivo de teste está errado, mas a esse ponto, se quiser, pode só ignorar essa parte. Um teste pontual não ter sido feito não vai prejudicar o desenvolvimento do projeto, diferentemente dos offsets arbritrários.

2024-10-04 16:53 UTC, Bassani-Paulo commented on Jogo/tests/unit/test_movement.gd
> +	var player = get_child(0) # Assuming the player is the only child
esse código não faz nenhum sentido. o filho adicionado à raiz na linha 8 chama-se double_jogo e aqui vocês o atribuem a uma variável chamada player.

2024-10-04 16:53 UTC, Bassani-Paulo commented on Jogo/tests/unit/test_movement.gd
> +	player.position.x += (400) * 2.88 # Simulate right movement
aqui você está movimentando o "player" (que não é o player devido à atribuição errada) a se mover. isso não está testando se ele se move com o comando.

2024-10-04 16:53 UTC, Bassani-Paulo commented on Jogo/tests/unit/test_movement.gd
> +	var expected_position_right = clamp(player.position.x, player.position.x - (400 * 2.88), player.position.x + (400 * 2.88))
aqui você está reescrevendo código, não é assim que se faz teste unitário. você "faz a conta na mão" da posição esperada após o movimento

2024-10-12 15:26 UTC, Bassani-Paulo requested changes

2024-10-12 15:26 UTC, Bassani-Paulo commented on Jogo/tests/test_movement.gd
não deveriam existir as variáveis test__pressed_left e test_pressed_right. invez disso, utilize: Input.action_press e Input.action_release

2024-10-12 15:26 UTC, Bassani-Paulo commented on Jogo/tests/test_movement.gd
> +	width = get_viewport().get_visible_rect().size.x
é uma má pratica utilizar um nome tão genérico. largura de que? é melhor algo do tipo viewport_width

2024-10-12 15:26 UTC, Bassani-Paulo commented on Jogo/tests/test_movement.gd
nos testes "out of bounds" não está invertido o grather than e less than? a tartaruga sai dos limites pela direita quando sua posição é maior do que o tamanho da tela. e pela esqueda quando a posição é menor do que 0.

2024-10-12 17:04 UTC, DaviGabrielBC commented on Jogo/scenes/Tartaruga/Jogo.tscn
> +scale = Vector2(2, 2)
Sem o scale, a texture da scene Jogo não preenche completamente a tela visível (800x600) além de que o espaço para a tartaruga se mover fica bem reduzido. Mas se quiser posso refazer os limites de movimento da tartaruga para condizer com o tamanho da Scene.

2024-10-12 17:39 UTC, DaviGabrielBC commented on Jogo/tests/test_movement.gd
Eu procurei bastante por funções desse jeito, em que fosse possível settar a Input, mas não achei. Inclusive essas funções que você citou parecem não existir, só achei as Input.is_action_pressed() e Input.is_action_released() que apenas retornam os valores da Input.

2024-10-12 21:46 UTC, Bassani-Paulo commented on Jogo/scenes/Tartaruga/Jogo.tscn
> +scale = Vector2(2, 2)
não se preocupe em como o background aparece na tela. o espaço de locomoção da tartaruga é limitado pelo tamanho do viewport e não do sprite de background.

2024-10-12 21:50 UTC, Bassani-Paulo commented on Jogo/tests/test_movement.gd
certamente não tentou Input.action_press. por exemplo: _Input.action_press("move_right")_

2024-10-12 22:06 UTC, Bassani-Paulo requested changes

2024-10-12 22:06 UTC, Bassani-Paulo commented on Jogo/tests/test_movement.gd
>  	player._process(2 * elapsed_time) # Enough time for the player to supposedly exceed the bounds of the visible rectangle
2*0.3 segundos é o suficiente para garantir que a tartaruga chegou na borda? coloque um tempo mais generoso. porquê a variável se chama elapsed_time? o que isso significa? aqui se quer um tempo suficiente para a tartaruga se deslocar para a borda, no outro teste se quer um tempo minimo para que a tartaruga se mova. porquê existe essa variável em ambos?

2024-10-13 02:39 UTC, DaviGabrielBC commented on Jogo/scenes/Tartaruga/Jogo.tscn
> +scale = Vector2(2, 2)
Isso, de fato a tartaruga não passa dos limites do retângulo visível, mas passa um pouco dos limites da Jogo.tscn. Para fins estéticos seria bom a gente expandir a scene. Por enquanto vou deixar diminuído pra dar o merge com tranquilidade, mais pra frente a gente pode decidir.

2024-10-13 02:43 UTC, DaviGabrielBC commented on Jogo/tests/test_movement.gd
>  	player._process(2 * elapsed_time) # Enough time for the player to supposedly exceed the bounds of the visible rectangle
Você acha melhor settar os valores manualmente então, algo como player._process(0.3) e player._process(3)? Elapsed_time significaria o tempo que o usuário passou com a tecla apertada na nossa simulação. Sim 0.6s é suficiente para chegar à borda, já que testei isso manualmente. Mas realmente vale a pena colocar um tempo maior como 3 segundos.

2024-10-13 03:16 UTC, Bassani-Paulo commented on Jogo/scenes/Tartaruga/Jogo.tscn
> +scale = Vector2(2, 2)
sim, isso vai ser resolvido em outra issue mais pra frente

2024-10-13 03:20 UTC, Bassani-Paulo commented on Jogo/tests/test_movement.gd
>  	player._process(2 * elapsed_time) # Enough time for the player to supposedly exceed the bounds of the visible rectangle
Nesse caso eu diria que sim. Quanto ao tempo, 3 segundos é ok.

2024-10-13 03:25 UTC, Bassani-Paulo submitted a review, later dismissed
Aprovado. Agora é só esperar o Márcio e o Gustavo aprovar que a gente faz o merge

2024-10-13 13:32 UTC, marcinholsp approved these changes

2024-10-13 13:40 UTC, merged