Mudanças no jogo da tarturaga
Bassani-Paulo/Projeto-MC656 pull request #47
Opened 2024-11-14 15:23 UTC by Caiozotex

Aqui está o código que resolve as issues #5 e #20

2024-11-19 18:37 UTC, DaviGabrielBC reviewed
Verificar se há conflitos com os outros commits que provavelmente serão efetuados. Fora isso, Super!! 🤯

2024-11-19 18:39 UTC, DaviGabrielBC submitted a review, later dismissed
Verificar se há conflitos com os outros pull requests que provavelmente serão efetuados antes deste. Fora isso, Super!! 🤯

2024-11-28 17:55 UTC, Bassani-Paulo requested changes
Nem todas as mudanças são necessárias. Não sei como diferenciar os comentários por relevância. Aqui vai uma visão geral:
O jogo está muito lento. tanto verticalmente quanto lateralmente, a tartaruga demora a chegar na borda. Quando o jogador perde uma vida, a dificuldade volta pra inicial sem limpar os canudos existentes o que pode fazer com que o jogdor perca mais vida antes deles saírem da tela. Além disso, a taxa mínima de 0.2 segundos entre canudos é muito baixa, isso gera situações onde é impossível o jogador desviar.

2024-11-28 17:55 UTC, Bassani-Paulo commented on Jogo/scripts/Tartaruga/Player.gd
> -	if get_viewport().get_visible_rect().size != Vector2.ZERO:
essa linha é importante para rodar no ambiete sem tela do servidor do github. tem outras formas de resolver, mas não da pra só remover sem resolver de outra forma

2024-11-28 17:55 UTC, Bassani-Paulo commented on Jogo/scripts/Tartaruga/Player.gd
> +var escala = 0.156
gambiarra, ao alterar o tamanho da tartaruga no futuro, não alterará automaticamente aqui o que vai causar bug. o correto é alterar o tamanho da textura original.

2024-11-28 17:55 UTC, Bassani-Paulo commented on Jogo/scripts/Tartaruga/Player.gd
> +	if velocity.length() > 0 :
if desnecessário. a solução anterior era mais eficiente

2024-11-28 17:55 UTC, Bassani-Paulo commented on Jogo/scripts/Tartaruga/Player.gd
> +	if area.name == "Area2D":
essa solução fará a tartaruga tomar dano em contato com qualquer coisa (inclusive comidas). essa não é a ideia

2024-11-28 17:55 UTC, Bassani-Paulo commented on Jogo/project.godot
não é legal utilizar um autoload e variáveis globais que se referem a apenas um mini jogo específico da aplicação. procure utilizar signals

2024-11-28 17:55 UTC, Bassani-Paulo commented on Jogo/scripts/Tartaruga/timer.gd
> +	canudo_speed = canudo.speed
onde essa variável recebe seu valor inicial? não encontrei

2024-11-28 17:55 UTC, Bassani-Paulo commented on Jogo/scripts/Tartaruga/lixo.gd
> +	print(canudo_height)
remover os prints depois de terminar a depuração

2024-12-02 12:30 UTC, merged